public typealias FullScaleAsyncNetworkController = ConfigurableAsyncNetworkController & LoggableAsyncNetworkController

public typealias FullScaleAsyncNetworkControllerDecorator = ConfigurableAsyncNetworkControllerDecorator & LoggableAsyncNetworkControllerDecorator
